version: '3'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  node-backend:
    build: ./node_graphql_crud_api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  
  react-frontend:
    build: ./to_do_frontend
    ports:
      - "5173:5173"

volumes:
  mongodb_data: